# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 18:12
from __future__ import unicode_literals

from django.db import migrations, models

tags_list = ['work', 'projects', 'shots and goggles']

def save_tags(apps schema_editor):
    Tag = apps.get_model('blog', 'Tag')
    for tag in tags_list:
        t = Tag(tag)
        t.save()

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('blog', '0005_auto_20170305_1630'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
